autoscale:
  environment:
    URL: ${URL}
    USER_NAME: ${ACCESS_KEY}
    KEY: ${SECRET_KEY}
    STACK_SERVICE_NAME: ${MONITOR_SERVICE}
    SCALE_SIZE: ${SCALE_SIZE}
    CPU_SCALE_PERCENT: ${CPU_SCALE_PERCENT}
    MEM_SCALE_VALUE: ${MEMORY_SCALE_VALUE}
    SCAN_INTERVAL: ${SCAN_INTERVALE}
    SCALE_RULE: ${SCALE_RULE}
    SCALE_MIN_MATCH_TIME: ${SCALE_MIN_MATCH_TIMES}
    SCALE_MIN: ${SCALE_MIN}
    SCALE_MAX: ${SCALE_MAX}
  labels:
#   io.rancher.container.pull_image: always
#    io.rancher.scheduler.affinity:host_label: hostname=host1
  tty: true
  command:
  - python
  - /home/autoscale.py
  image: index.youruncloud.com/huayun.yu/autoscale:v2.0.0
  stdin_open: true

